### PR TITLE
Fit and transform method for a stain normalizer

### PR DESCRIPTION
**Pull request by take5v**
Hi,

The fit_transform method could be used for a single image normalization (or small set of low contrast images).

Best regards,
Stas

### CODE REVIEW

**Comment by Peter554** [comment]
Thanks for the interest! But aren't you in this case fitting and transforming to the same image? In which case in an ideal world you should just get the original image back? I may be missing the point?

**Comment by take5v** [comment]
Yes, I agree, it is a stupid idea.

For image registration, I'd like to obtain a "better" grayscale representation from RGB histological image. I mean, somehow better than taking Y from simple linear YCbCr formula.

I also thought to take the mean of H and E at the concentration matrix (after deconvolution). Is it worth to do like this?

Best regards,
Stas

**Comment by Peter554** [comment]
No it's not a bad idea necessarily. In the past I have known people to just use a grayscale Hematoxylin image. In that case you could do something like (just a sketch - not tested):

```python
extractor = VahadaneStainExtractor

stain_matrix = extractor.get_stain_matrix(my_image)
concentrations = get_concentrations(my_image, stain_matrix)
hemo_optical_density = concentrations[:, 0]

hemo = np.exp(-1 * hemo_optical_density)
# Scale image to a sensible range
hemo = 255 * hemo / np.max(hemo)
# Only user shape[0, -1] as my_image is RGB but hemo is grayscale.
hemo = hemo.reshape(my_image.shape[0, -1]).astype(np.uint8)
```

**Comment by take5v** [comment]
Thanks for the sketch! I'll close this PR since it makes no sense to fit and transform the same image.

Would you like to have a grayscale conversion somewhere at your StainTools? :)
It can be 1) Eosin concentration, 2) Hematoxylin concentration and 3) sum of concentrations (E+H) - grayscale OD converted then to an intensity.

**Pull request closed without merging**
